2021/11/01 14:42:10 [emerg] 80192#0: bind() to 0.0.0.0:3000 failed (98: Address already in use)
2021/11/01 14:42:10 [emerg] 80192#0: bind() to 0.0.0.0:3000 failed (98: Address already in use)
2021/11/01 14:42:10 [emerg] 80192#0: bind() to 0.0.0.0:3000 failed (98: Address already in use)
2021/11/01 14:42:10 [emerg] 80192#0: bind() to 0.0.0.0:3000 failed (98: Address already in use)
2021/11/01 14:42:10 [emerg] 80192#0: bind() to 0.0.0.0:3000 failed (98: Address already in use)
2021/11/01 14:42:10 [emerg] 80192#0: still could not bind()
[ N 2021-11-01 14:43:59.9406 80598/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:43:59.9500 80601/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:43:59.9500 80601/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:43:59.9947 80601/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 80601
[ N 2021-11-01 14:44:02.2192 80601/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 80656 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 80656 output:     config.ru:2:in `require'
App 80656 output:     config.ru:2:in `block in <main>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 80656 output:     config.ru:1:in `new'
App 80656 output:     config.ru:1:in `<main>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 80656 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:44:02.3935 80601/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 1930ade7
  Error details saved to: /tmp/passenger-error-icphaT.html

[ E 2021-11-01 14:44:02.4050 80601/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1930ade7. Please see earlier logs for details about the error.

[ N 2021-11-01 14:44:19.8161 80601/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:44:19.8162 80601/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:44:19.8164 80601/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8164 80601/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8164 80601/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8165 80601/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:44:19.8165 80601/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:44:19.8164 80601/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8165 80601/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8165 80601/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8165 80601/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:44:19.8166 80601/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:44:19.8166 80601/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8166 80601/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:44:19.8166 80601/Tj Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8167 80601/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:44:19.8167 80601/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:44:19.8167 80601/Tj Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:44:19.8168 80601/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8168 80601/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:44:19.8168 80601/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8169 80601/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:44:19.8169 80601/Tn Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8169 80601/Tx Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8169 80601/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:44:19.8169 80601/Tn Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:44:19.8169 80601/Tx Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:44:19.8170 80601/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:44:20.3413 80601/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 14:45:11.2830 80879/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:45:11.2922 80883/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:45:11.2923 80883/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:45:11.3427 80883/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 80883
[ N 2021-11-01 14:45:13.5663 80883/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 80937 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 80937 output:     config.ru:2:in `require'
App 80937 output:     config.ru:2:in `block in <main>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 80937 output:     config.ru:1:in `new'
App 80937 output:     config.ru:1:in `<main>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 80937 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:45:13.7137 80883/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: efbd9311
  Error details saved to: /tmp/passenger-error-NbFc99.html

[ E 2021-11-01 14:45:13.7169 80883/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is efbd9311. Please see earlier logs for details about the error.

[ N 2021-11-01 14:45:23.0502 80883/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:45:23.0502 80883/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:45:23.0503 80883/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Tj Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0503 80883/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/Tj Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0504 80883/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:45:23.0504 80883/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:45:23.0504 80883/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:45:23.0503 80883/Th Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0504 80883/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:45:23.0504 80883/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0504 80883/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0504 80883/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:45:23.0504 80883/Th Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:45:23.0504 80883/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:45:23.0505 80883/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:45:23.0505 80883/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:45:23.3720 80883/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 14:45:28.4923 81039/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:45:28.5032 81043/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:45:28.5034 81043/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:45:28.5391 81043/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 81043
[ N 2021-11-01 14:45:30.7676 81043/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 81108 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 81108 output:     config.ru:2:in `require'
App 81108 output:     config.ru:2:in `block in <main>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 81108 output:     config.ru:1:in `new'
App 81108 output:     config.ru:1:in `<main>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 81108 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:45:30.9838 81043/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 0a99e0ce
  Error details saved to: /tmp/passenger-error-AjZCVg.html

[ E 2021-11-01 14:45:30.9942 81043/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 0a99e0ce. Please see earlier logs for details about the error.
App 81156 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 81156 output:     config.ru:2:in `require'
App 81156 output:     config.ru:2:in `block in <main>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 81156 output:     config.ru:1:in `new'
App 81156 output:     config.ru:1:in `<main>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 81156 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:45:42.4377 81043/T14 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: ae64c341
  Error details saved to: /tmp/passenger-error-5AzwTf.html

[ E 2021-11-01 14:45:42.4473 81043/Ta age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is ae64c341. Please see earlier logs for details about the error.
App 81237 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 81237 output:     config.ru:2:in `require'
App 81237 output:     config.ru:2:in `block in <main>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 81237 output:     config.ru:1:in `new'
App 81237 output:     config.ru:1:in `<main>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 81237 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:45:44.3715 81043/T19 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: ea117458
  Error details saved to: /tmp/passenger-error-a2DGwh.html

[ E 2021-11-01 14:45:44.3760 81043/Tc age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is ea117458. Please see earlier logs for details about the error.

[ N 2021-11-01 14:45:48.8470 81043/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:45:48.8471 81043/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:45:48.8471 81043/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8471 81043/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:45:48.8471 81043/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8471 81043/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:45:48.8471 81043/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8471 81043/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8471 81043/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8471 81043/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:45:48.8472 81043/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:45:48.8472 81043/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:45:49.2022 81043/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 14:46:47.4373 81527/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:46:47.4473 81530/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:46:47.4474 81530/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:46:47.5001 81530/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 81530
[ N 2021-11-01 14:46:49.7743 81530/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 81585 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 81585 output:     config.ru:2:in `require'
App 81585 output:     config.ru:2:in `block in <main>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 81585 output:     config.ru:1:in `new'
App 81585 output:     config.ru:1:in `<main>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 81585 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:46:49.8942 81530/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: fa9ba86c
  Error details saved to: /tmp/passenger-error-h4AUJ7.html

[ E 2021-11-01 14:46:49.9046 81530/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is fa9ba86c. Please see earlier logs for details about the error.

[ N 2021-11-01 14:46:52.0921 81530/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:46:52.0921 81530/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:46:52.0922 81530/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Th Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:46:52.0922 81530/Tl Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:46:52.0922 81530/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0922 81530/Th Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:46:52.0922 81530/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:46:52.0922 81530/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0923 81530/Tl Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0923 81530/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0923 81530/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0923 81530/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:46:52.0923 81530/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:46:52.0923 81530/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:46:52.3987 81530/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 14:54:45.5454 82809/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:54:45.5553 82812/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:54:45.5553 82812/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:54:45.6680 82812/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 82812
App 82876 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 82876 output:     config.ru:2:in `require'
App 82876 output:     config.ru:2:in `block in <main>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 82876 output:     config.ru:1:in `new'
App 82876 output:     config.ru:1:in `<main>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 82876 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:54:48.0484 82812/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 70d05656
  Error details saved to: /tmp/passenger-error-EL4Z72.html

[ E 2021-11-01 14:54:48.0530 82812/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 70d05656. Please see earlier logs for details about the error.
[ N 2021-11-01 14:54:48.1533 82812/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 82975 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 82975 output:     config.ru:2:in `require'
App 82975 output:     config.ru:2:in `block in <main>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 82975 output:     config.ru:1:in `new'
App 82975 output:     config.ru:1:in `<main>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 82975 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:54:57.0140 82812/T14 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: fd8dc634
  Error details saved to: /tmp/passenger-error-ZxnRP3.html

[ E 2021-11-01 14:54:57.0169 82812/Ta age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is fd8dc634. Please see earlier logs for details about the error.
App 83022 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 83022 output:     config.ru:2:in `require'
App 83022 output:     config.ru:2:in `block in <main>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 83022 output:     config.ru:1:in `new'
App 83022 output:     config.ru:1:in `<main>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 83022 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 14:54:57.6651 82812/T19 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 5e95c250
  Error details saved to: /tmp/passenger-error-mxafT2.html

[ E 2021-11-01 14:54:57.6682 82812/Tc age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 5e95c250. Please see earlier logs for details about the error.

[ N 2021-11-01 14:55:13.1949 82812/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:55:13.1950 82812/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:55:13.1950 82812/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1951 82812/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1951 82812/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:55:13.1951 82812/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1951 82812/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1951 82812/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1952 82812/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1952 82812/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1952 82812/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:55:13.1952 82812/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1953 82812/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:55:13.1955 82812/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:55:13.1953 82812/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1953 82812/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:55:13.1953 82812/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:55:13.1954 82812/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:55:13.1954 82812/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:55:13.1955 82812/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:55:13.1955 82812/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1955 82812/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1956 82812/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1956 82812/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:55:13.1956 82812/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:55:13.1957 82812/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:55:13.1956 82812/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:55:13.1957 82812/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:55:13.5266 82812/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 14:55:30.4501 83138/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 14:55:30.4599 83141/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 14:55:30.4600 83141/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 14:55:30.5165 83141/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 83141

[ N 2021-11-01 14:55:31.7686 83141/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 14:55:31.7687 83141/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 14:55:31.7688 83141/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tt Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tl Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7688 83141/Tt Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7689 83141/Tl Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 14:55:31.7689 83141/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7689 83141/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 14:55:31.7689 83141/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 14:55:31.7688 83141/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 14:55:31.7690 83141/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 14:55:32.3015 83141/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:09:03.9302 84657/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:09:03.9397 84660/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:09:03.9398 84660/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:09:04.0078 84660/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 84660
[ N 2021-11-01 15:09:06.2281 84660/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 84716 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 84716 output:     config.ru:2:in `require'
App 84716 output:     config.ru:2:in `block in <main>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 84716 output:     config.ru:1:in `new'
App 84716 output:     config.ru:1:in `<main>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 84716 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:09:06.4305 84660/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: ca26bd8b
  Error details saved to: /tmp/passenger-error-nzXZlP.html

[ E 2021-11-01 15:09:06.4411 84660/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is ca26bd8b. Please see earlier logs for details about the error.

[ N 2021-11-01 15:09:07.7251 84660/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:09:07.7252 84660/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:09:07.7253 84660/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7253 84660/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:09:07.7253 84660/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7254 84660/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7254 84660/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/Tv Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7254 84660/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7254 84660/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:09:07.7254 84660/Tv Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:09:07.7254 84660/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:09:08.9911 84660/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:11:26.5382 85169/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:11:26.5487 85172/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:11:26.5488 85172/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:11:26.6099 85172/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 85172
App 85227 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 85227 output:     config.ru:2:in `require'
App 85227 output:     config.ru:2:in `block in <main>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 85227 output:     config.ru:1:in `new'
App 85227 output:     config.ru:1:in `<main>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 85227 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ N 2021-11-01 15:11:28.9560 85172/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
[ E 2021-11-01 15:11:28.9920 85172/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: ab715887
  Error details saved to: /tmp/passenger-error-gdcmrv.html

[ E 2021-11-01 15:11:28.9958 85172/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is ab715887. Please see earlier logs for details about the error.

[ N 2021-11-01 15:12:42.4172 85172/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:12:42.4172 85172/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:12:42.4174 85172/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4174 85172/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4174 85172/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4174 85172/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4175 85172/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:12:42.4175 85172/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:12:42.4175 85172/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4175 85172/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:12:42.4176 85172/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:12:42.4176 85172/Tl Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4176 85172/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:12:42.4176 85172/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4177 85172/Tl Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:12:42.4177 85172/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:12:42.4178 85172/Tp Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4178 85172/Tn Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4178 85172/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4178 85172/Tn Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:12:42.4178 85172/Tp Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:12:42.4178 85172/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4178 85172/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4179 85172/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:12:42.4179 85172/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:12:42.4179 85172/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:12:42.4180 85172/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:12:42.4181 85172/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:12:42.7508 85172/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:13:08.7742 85407/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:13:08.7836 85410/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:13:08.7836 85410/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:13:08.8361 85410/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 85410
[ N 2021-11-01 15:13:11.0580 85410/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 85470 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 85470 output:     config.ru:2:in `require'
App 85470 output:     config.ru:2:in `block in <main>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 85470 output:     config.ru:1:in `new'
App 85470 output:     config.ru:1:in `<main>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 85470 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:13:11.1846 85410/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: a2829468
  Error details saved to: /tmp/passenger-error-6crHYs.html

[ E 2021-11-01 15:13:11.1881 85410/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is a2829468. Please see earlier logs for details about the error.

[ N 2021-11-01 15:13:16.0924 85410/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:13:16.0925 85410/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:13:16.0925 85410/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Tn Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0926 85410/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tn Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:13:16.0927 85410/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:13:16.0927 85410/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0927 85410/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:13:16.0926 85410/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:13:16.0927 85410/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:13:16.0927 85410/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:13:17.5072 85410/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:14:00.9427 85557/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:14:00.9515 85560/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:14:00.9515 85560/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:14:01.0146 85560/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 85560
[ N 2021-11-01 15:14:03.2350 85560/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 85617 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 85617 output:     config.ru:2:in `require'
App 85617 output:     config.ru:2:in `block in <main>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 85617 output:     config.ru:1:in `new'
App 85617 output:     config.ru:1:in `<main>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 85617 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:14:03.3625 85560/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: c7565fef
  Error details saved to: /tmp/passenger-error-vhoxDQ.html

[ E 2021-11-01 15:14:03.3659 85560/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is c7565fef. Please see earlier logs for details about the error.

[ N 2021-11-01 15:14:07.0292 85560/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:14:07.0293 85560/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:14:07.0293 85560/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0293 85560/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Tr Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0294 85560/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:14:07.0294 85560/Tv Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0294 85560/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:14:07.0294 85560/Tr Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:14:07.0294 85560/Tv Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:14:07.0293 85560/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0294 85560/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:14:07.0294 85560/Tt Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0294 85560/Tx Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:14:07.0294 85560/Tt Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:14:07.0294 85560/Tx Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:14:07.3677 85560/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:17:04.9771 86226/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:17:04.9889 86229/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:17:04.9890 86229/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:17:05.0274 86229/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 86229
App 86284 output: Error: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
App 86284 output:     config.ru:3:in `require'
App 86284 output:     config.ru:3:in `block in <main>'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 86284 output:     config.ru:1:in `new'
App 86284 output:     config.ru:1:in `<main>'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 86284 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:17:07.4466 86229/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
  Error ID: c0526514
  Error details saved to: /tmp/passenger-error-ERYb2r.html

[ E 2021-11-01 15:17:07.4493 86229/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is c0526514. Please see earlier logs for details about the error.
[ N 2021-11-01 15:17:07.5741 86229/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 86334 output: Error: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
App 86334 output:     config.ru:3:in `require'
App 86334 output:     config.ru:3:in `block in <main>'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 86334 output:     config.ru:1:in `new'
App 86334 output:     config.ru:1:in `<main>'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 86334 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:17:10.7038 86229/T14 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
  Error ID: 344695ea
  Error details saved to: /tmp/passenger-error-WEoJUp.html

[ E 2021-11-01 15:17:10.7074 86229/Tb age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 344695ea. Please see earlier logs for details about the error.
App 86398 output: Error: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
App 86398 output:     config.ru:3:in `require'
App 86398 output:     config.ru:3:in `block in <main>'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 86398 output:     config.ru:1:in `new'
App 86398 output:     config.ru:1:in `<main>'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 86398 output:     /home/ehetzel/src/random/deloitte/ruby/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-01 15:17:11.1472 86229/T19 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/ehetzel/src/random/deloitte/ruby: The application encountered the following error: cannot load such file -- /home/ehetzel/src/random/deloitte/ruby/config.ru/app.rb (LoadError)
  Error ID: 2f320159
  Error details saved to: /tmp/passenger-error-KQwDip.html

[ E 2021-11-01 15:17:11.1578 86229/Tc age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 2f320159. Please see earlier logs for details about the error.

[ N 2021-11-01 15:17:14.9549 86229/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:17:14.9550 86229/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:17:14.9552 86229/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9552 86229/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9552 86229/Te Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9552 86229/Tg Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9552 86229/Tb Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9553 86229/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:17:14.9553 86229/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:17:14.9553 86229/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:17:14.9553 86229/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:17:14.9554 86229/Tb Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:17:14.9554 86229/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9555 86229/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:17:14.9555 86229/Tt Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9555 86229/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9555 86229/Tt Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:17:14.9555 86229/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:17:14.9555 86229/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9556 86229/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:17:14.9556 86229/Tk Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9556 86229/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:17:14.9556 86229/Tr Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9557 86229/Tr Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:17:14.9558 86229/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9558 86229/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:17:14.9559 86229/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:17:14.9559 86229/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:17:15.8865 86229/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2021-11-01 15:17:20.4395 86495/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-11-01 15:17:20.4494 86498/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-11-01 15:17:20.4496 86498/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-11-01 15:17:20.4804 86498/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 86498
[ N 2021-11-01 15:17:22.6842 86498/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 86590 output: 127.0.0.1 - - [01/Nov/2021:15:17:22 +0100] "HEAD / HTTP/1.1" 200 1739 0.0007
App 86590 output: 127.0.0.1 - - [01/Nov/2021:15:17:27 +0100] "GET / HTTP/1.1" 200 1739 0.0043
App 86590 output: 127.0.0.1 - - [01/Nov/2021:15:17:27 +0100] "GET /favicon.ico HTTP/1.1" 404 469 0.0006

[ N 2021-11-01 15:17:40.6636 86498/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2021-11-01 15:17:40.6637 86498/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2021-11-01 15:17:40.6638 86498/T1 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 86590, application /home/ehetzel/src/random/deloitte/ruby (development)
[ N 2021-11-01 15:17:40.6641 86498/Tc Ser/Server.h:902 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/Tf Ser/Server.h:902 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/Ti Ser/Server.h:902 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/Tm Ser/Server.h:902 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/Th Ser/Server.h:902 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/Ta Ser/Server.h:902 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6642 86498/Tl Ser/Server.h:902 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6641 86498/T8 Ser/Server.h:902 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6642 86498/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2021-11-01 15:17:40.6642 86498/Tf Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2021-11-01 15:17:40.6642 86498/Tq Ser/Server.h:902 ]: [ServerThr.10] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6642 86498/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2021-11-01 15:17:40.6643 86498/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2021-11-01 15:17:40.6643 86498/Th Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2021-11-01 15:17:40.6643 86498/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2021-11-01 15:17:40.6643 86498/Tl Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2021-11-01 15:17:40.6644 86498/Tq Ser/Server.h:558 ]: [ServerThr.10] Shutdown finished
[ N 2021-11-01 15:17:40.6644 86498/Ts Ser/Server.h:902 ]: [ServerThr.11] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6644 86498/To Ser/Server.h:902 ]: [ServerThr.9] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6644 86498/Tw Ser/Server.h:902 ]: [ApiServer] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6645 86498/Ts Ser/Server.h:558 ]: [ServerThr.11] Shutdown finished
[ N 2021-11-01 15:17:40.6645 86498/Tu Ser/Server.h:902 ]: [ServerThr.12] Freed 0 spare client objects
[ N 2021-11-01 15:17:40.6645 86498/To Ser/Server.h:558 ]: [ServerThr.9] Shutdown finished
[ N 2021-11-01 15:17:40.6645 86498/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2021-11-01 15:17:40.6645 86498/Tw Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2021-11-01 15:17:40.6646 86498/Tu Ser/Server.h:558 ]: [ServerThr.12] Shutdown finished
[ N 2021-11-01 15:17:40.6648 86498/T1 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 86590, application /home/ehetzel/src/random/deloitte/ruby (development)
[ N 2021-11-01 15:17:41.4169 86498/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
